var arquitectura = [
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Taller de Proyectos 1", UC: 11, Tax: "TA‐8" },
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Cálculo Infinitesimal para Arquitectura ",
		UC: 5,
		Tax: "TA‐4",
	},
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Dibujo", UC: 3, Tax: "TA‐9" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Historia, Teoría y Crítica I", UC: 3, Tax: "TA‐1" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Tecnología y Arquitectura", UC: 5, Tax: "TA‐6" },
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso I",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Competencia Textual en Español",
		UC: 5,
		Tax: "TA-6",
	},

	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Taller de Proyectos 2", UC: 11, Tax: "TA‐8" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Modelización Arquitectónica", UC: 3, Tax: "TA‐4" },
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Historia, Teoría y Crítica II ",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Ecología, Ambiente y Sustentabilidad ",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Cálculo Diferencial e Integral para Arquitectura",
		UC: 5,
		Tax: "TA‐4",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso II ",
		UC: 3,
		Tax: "TA‐1",
	},

	{ Semestre: "TERCER SEMESTRE", Asignatura: "Taller de Proyectos 3", UC: 11, Tax: "TA‐8" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Dibujo II", UC: 3, Tax: "TA‐9" },
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Historia, Teoría y Crítica III",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Diseño Estructural ",
		UC: 4,
		Tax: "TA‐3",
	},
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Ambiente y Arquitectura", UC: 3, Tax: "TA‐1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Geometría Descriptiva I", UC: 8, Tax: "TA-4" },

	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Taller de Proyectos 4", UC: 11, Tax: "TA‐8" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Dibujo Asistido por Computadora",
		UC: 2,
		Tax: "TA‐9",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Historia, Teoría y Crítica IV ",
		UC: 3,
		Tax: "TA‐1",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Estudios Urbanos I ", UC: 4, Tax: "TA‐3" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Impacto Ambiental ", UC: 3, Tax: "TA‐9" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Materiales de Construcción", UC: 4, Tax: "TA‐4" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Laboratorio de Materiales de Construcción ",
		UC: 2,
		Tax: "TA‐9",
	},

	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Taller de Proyectos 5", UC: 11, Tax: "TA‐8" },
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Dibujo Asistido por Computadora II",
		UC: 2,
		Tax: "TA‐9",
	},
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Historia, Teoría y Crítica V", UC: 3, Tax: "TA‐1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Estudios Urbanos II ", UC: 4, Tax: "TA‐3" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Turismo y Ambiente ", UC: 3, Tax: "TA‐1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Instalaciones Eléctricas ", UC: 2, Tax: "TA‐8" },

	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Taller de Proyectos 6", UC: 11, Tax: "TA‐8" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Taller de Fotografía", UC: 4, Tax: "TA‐8" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Arquitectura Latinoamericana", UC: 3, Tax: "TA-1" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Análisis Urbano", UC: 3, Tax: "TA‐1" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Instalaciones Sanitarias para Edificaciones",
		UC: 4,
		Tax: "TA‐9",
	},
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Innovación y Emprendimiento", UC: 3, Tax: "TA‐1" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Innovación y Emprendimiento (Virtual)",
		UC: 3,
		Tax: "TA‐1 (V)",
	},

	{ Semestre: "SEPTIMO SEMESTRE", Asignatura: "Taller de Proyectos 7", UC: 11, Tax: "TA‐8" },
	{
		Semestre: "SEPTIMO SEMESTRE",
		Asignatura: "Laboratorio de Fabricación Digital",
		UC: 4,
		Tax: "TA‐9",
	},
	{ Semestre: "SEPTIMO SEMESTRE", Asignatura: "Obras y Arquitectos ", UC: 3, Tax: "TA‐1" },
	{
		Semestre: "SEPTIMO SEMESTRE",
		Asignatura: "Fundamentos del Diseño Urbano ",
		UC: 3,
		Tax: "TA‐1",
	},
	{ Semestre: "SEPTIMO SEMESTRE", Asignatura: "Taller de Tecnología ", UC: 5, Tax: "TA‐4" },

	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Taller de Proyectos 8", UC: 11, Tax: "TA‐8" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Comunicación Efectiva ", UC: 3, Tax: "TA‐1" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Reflexión y Crítica", UC: 3, Tax: "TA‐1" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Asentamientos Informales", UC: 3, Tax: "TA‐1" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Laboratorio de Fabricación ", UC: 4, Tax: "TA‐9" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Etica Profesional ", UC: 3, Tax: "TA‐2 (SP)" },

	{ Semestre: "NOVENO SEMESTRE", Asignatura: "Taller de Proyectos 9", UC: 11, Tax: "TA‐8" },
	{ Semestre: "NOVENO SEMESTRE", Asignatura: " Electiva de Representación", UC: 3, Tax: "TA‐1" },
	{ Semestre: "NOVENO SEMESTRE", Asignatura: "Seminario de Investigación", UC: 5, Tax: "TA‐1" },
	{ Semestre: "NOVENO SEMESTRE", Asignatura: "Electiva de Proyectos", UC: 3, Tax: "TA‐1" },
	{ Semestre: "NOVENO SEMESTRE", Asignatura: "Electiva de Tecnología ", UC: 3, Tax: "TA‐1" },
	{ Semestre: "NOVENO SEMESTRE", Asignatura: "Pasantía Especializada", UC: 5, Tax: "TA‐7" },
	{ Semestre: "NOVENO SEMESTRE", Asignatura: "Normativa Aplicada", UC: 3, Tax: "TA‐1" },

	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Taller de Proyectos 10", UC: 11, Tax: "TA‐3" },
	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Electiva de Representación", UC: 3, Tax: "TA‐1" },
	{
		Semestre: "DECIMO SEMESTRE",
		Asignatura: "Seminario de Trabajo de Grado",
		UC: 2,
		Tax: "TA‐9",
	},
	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Electiva de Proyectos", UC: 3, Tax: "TA‐1" },
	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Electiva de Tecnología ", UC: 3, Tax: "TA‐1" },
	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Inglés Instrumental ", UC: 4, Tax: "TA‐1" },
	{
		Semestre: "DECIMO SEMESTRE",
		Asignatura: "Inglés Instrumental (Virtual)",
		UC: 4,
		Tax: "TA‐1 (V)",
	},
];
