var comunicacionsocialanteriorpensum = [
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Competencia Textual en Español",
		UC: 5,
		Tax: "TA-6",
	},
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Fundamentos de Gramática", UC: 5, Tax: "TA-4" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Comunicación Oral", UC: 4, Tax: "TA-8" },
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Teoría y Práctica de la Argumentación",
		UC: 5,
		Tax: "TA-3",
	},
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Cultura y Premodernidad", UC: 6, Tax: "TA-3" },
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Comprensión de Textos en Inglés",
		UC: 5,
		Tax: "TA-6",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso I",
		UC: 3,
		Tax: "TA-1",
	},
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Comunicación Escrita I", UC: 4, Tax: "TA-8" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Literatura y Comunicación", UC: 6, Tax: "TA-3" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Cultura y Modernidad", UC: 6, Tax: "TA-3" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Teoría de la Comunicación", UC: 6, Tax: "TA-1" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Arte y Comunicación", UC: 5, Tax: "TA-1" },
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso II",
		UC: 3,
		Tax: "TA-1",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Producción de Contenidos en Inglés",
		UC: 5,
		Tax: "TA-6",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Producción de Contenidos para Medios I",
		UC: 4,
		Tax: "TA-9",
	},

	{ Semestre: "TERCER SEMESTRE", Asignatura: "Economía", UC: 5, Tax: "TA-3" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Cultura y Posmodernidad", UC: 6, Tax: "TA-3" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Comunicación Escrita II", UC: 4, Tax: "TA-8" },
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Historia de Venezuela en los Medios I",
		UC: 6,
		Tax: "TA-3",
	},
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Psicología Social", UC: 6, Tax: "TA-3" },
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Ecología, Ambiente y Sustentabilidad",
		UC: 3,
		Tax: "TA-1",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Comunicación Gráfica", UC: 4, Tax: "TA-9" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Producción de Contenidos para Medios II",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Principios de Marketing",
		UC: 5,
		Tax: "TA-1",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Mercadeo", UC: 5, Tax: "TA-4" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Historia de Venezuela en los Medios II",
		UC: 6,
		Tax: "TA-3",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Sociología Política", UC: 6, Tax: "TA-3" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Ética de la Comunicación Social",
		UC: 6,
		Tax: "TA-1",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Estadística", UC: 5, Tax: "TA-4" },
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Sociología de la Comunicación",
		UC: 5,
		Tax: "TA-1",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Régimen Jurídico de la Comunicación",
		UC: 5,
		Tax: "TA-1",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Fundamentos de Comunicaciones Integradas de Mercadeo",
		UC: 5,
		Tax: "TA-1",
	},
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Comunicación Escénica", UC: 5, Tax: "TA-3" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Artes Audiovisuales", UC: 5, Tax: "TA-2" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Semiótica", UC: 5, Tax: "TA-1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Metodología", UC: 5, Tax: "TA-6" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Procesos editoriales", UC: 5, Tax: "TA-2" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Procesos editoriales (Virtual)",
		UC: 5,
		Tax: "TA-2 (V)",
	},
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Periodismo", UC: 4, Tax: "TA-9" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Teorías Administrativas de la Organización",
		UC: 3,
		Tax: "TA-1",
	},
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "(Virtual) Teorías Administrativas de la Organización",
		UC: 3,
		Tax: "(V) TA-1",
	},
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Fundamentos de Guión", UC: 5, Tax: "TA-4" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Gestión Cultural", UC: 5, Tax: "TA-2" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "(Virtual) Gestión Cultural",
		UC: 5,
		Tax: "(V) TA-2",
	},
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Opinión Pública", UC: 5, Tax: "TA-2" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Gerencia de Proyectos", UC: 5, Tax: "TA-4" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Innovación y Emprendimiento", UC: 3, Tax: "TA-1" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Innovación y Emprendimiento (Virtual)",
		UC: 3,
		Tax: "TA-1 (V)",
	},

	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE A",
		Asignatura: "Comunicaciones Organizacionales",
		UC: 6,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE A",
		Asignatura: "Comunicaciones Internas y Externas",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE A",
		Asignatura: "Relaciones Públicas",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE A",
		Asignatura: "Comunicaciones Digitales",
		UC: 3,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE A",
		Asignatura: "Comunicaciones Digitales (Virtual)",
		UC: 3,
		Tax: "TA-1 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE A",
		Asignatura: "Planificación y Gestión de Eventos",
		UC: 5,
		Tax: "TA-5",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE A",
		Asignatura: "Electiva Presencial",
		UC: 3,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE A",
		Asignatura: "Electiva Virtual",
		UC: 3,
		Tax: "TA-4 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE B",
		Asignatura: "Vocería y Telegenia",
		UC: 4,
		Tax: "TA-8",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE B",
		Asignatura: "Responsabilidad Social Empresarial y Desarrollo Sustentable",
		UC: 3,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE B",
		Asignatura: "(Virtual) Responsabilidad Social Empresarial y Desarrollo Sustentable ",
		UC: 3,
		Tax: "TA-2 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE B",
		Asignatura: "Políticas Comunicacionales Corporativas",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE B",
		Asignatura: "Gerencia de la Comunicación en Crisis",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE B",
		Asignatura: "Trabajo Final de la Concentración Comunicaciones Corporativas",
		UC: 6,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE B",
		Asignatura: "Electiva Presencial",
		UC: 3,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES CORPORATIVAS SEMESTRE B",
		Asignatura: "Electiva Virtual",
		UC: 3,
		Tax: "TA-4 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE A",
		Asignatura: "Comunicaciones Integradas de Mercadeo",
		UC: 4,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE A",
		Asignatura: "Publicidad",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE A",
		Asignatura: "Investigación de Mercado",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE A",
		Asignatura: "Canales de Comercialización",
		UC: 3,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE A",
		Asignatura: "Comportamiento del Consumidor",
		UC: 6,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE A",
		Asignatura: "Electiva Presencial",
		UC: 3,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE A",
		Asignatura: "Electiva Virtual",
		UC: 3,
		Tax: "TA-4 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE B",
		Asignatura: "Campañas Publicitarias",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE B",
		Asignatura: "Mercadeo de Servicios",
		UC: 3,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE B",
		Asignatura: "Mercadeo Digital",
		UC: 5,
		Tax: "TA-2 (SP)",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE B",
		Asignatura: "Estrategias de Mercadeo",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE B",
		Asignatura: "Electiva Presencial",
		UC: 3,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE B",
		Asignatura: "Electiva Virtual",
		UC: 3,
		Tax: "TA-4 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN COMUNICACIONES INTEGRADAS DE\nMERCADEO SEMESTRE B",
		Asignatura: "Trabajo Final de la Concentración Comunicaciones Integradas de Mercadeo",
		UC: 6,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE A",
		Asignatura: "Videografía ",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE A",
		Asignatura: "Historia del Cine",
		UC: 3,
		Tax: "TA-1",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE A",
		Asignatura: "Postproducción",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE A",
		Asignatura: "Electiva Presencial",
		UC: 3,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE A",
		Asignatura: "Electiva Virtual",
		UC: 3,
		Tax: "TA-4 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE A",
		Asignatura: "Televisión",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE A",
		Asignatura: "Fotografía",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE A",
		Asignatura: "Producción Cinematográfica",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE B",
		Asignatura: "Investigación Audiovisual",
		UC: 4,
		Tax: "TA-2 (SP)",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE B",
		Asignatura: "Documental",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE B",
		Asignatura: "Realización Cinematográfica",
		UC: 5,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE B",
		Asignatura: "Sonido",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE B",
		Asignatura: "Radio",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE B",
		Asignatura: "Electiva Presencial",
		UC: 3,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE B",
		Asignatura: "Electiva Virtual",
		UC: 3,
		Tax: "TA-4 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN PRODUCCIÓN AUDIOVISUAL SEMESTRE B",
		Asignatura: "Trabajo Final de la Concentración en Producción Audiovisual",
		UC: 6,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE A",
		Asignatura: "Estructura Dramática",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE A",
		Asignatura: "Análisis Fílmico",
		UC: 4,
		Tax: "TA-2 (SP)",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE A",
		Asignatura: "Personajes y Diálogos",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE A",
		Asignatura: "Guión para Cine I",
		UC: 5,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE A",
		Asignatura: "Narrativas Transmedia",
		UC: 3,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE A",
		Asignatura: "Electiva Presencial",
		UC: 3,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE A",
		Asignatura: "Electiva Virtual",
		UC: 3,
		Tax: "TA-4 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE B",
		Asignatura: "Adaptación Cinematográfica",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE B",
		Asignatura: "Guión para Cine II",
		UC: 5,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE B",
		Asignatura: "Guión para Seriado",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE B",
		Asignatura: "Guión para Telenovela",
		UC: 5,
		Tax: "TA-4",
	},
	{ Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE B", Asignatura: "Electiva", UC: 3, Tax: "TA-4" },
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE B",
		Asignatura: "Electiva Virtual",
		UC: 3,
		Tax: "(V) TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN GUIONISMO SEMESTRE B",
		Asignatura: "Trabajo Final de la Concentración en Guionismo",
		UC: 6,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE A",
		Asignatura: "Géneros Dialógicos",
		UC: 5,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE A",
		Asignatura: "Producción de Contenidos Editoriales",
		UC: 4,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE A",
		Asignatura: "Análisis de Medios Periodísticos y Audiencias",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE A",
		Asignatura: "Gestión de Medios Informativos",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE A",
		Asignatura: "Narrativas Audiovisuales",
		UC: 5,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE A",
		Asignatura: "Electiva Presencial",
		UC: 3,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE A",
		Asignatura: "Electiva Virtual",
		UC: 3,
		Tax: "TA-4 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE B",
		Asignatura: "Géneros Interpretativos",
		UC: 5,
		Tax: "TA-9",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE B",
		Asignatura: "(Virtual) Deontología Periodística",
		UC: 4,
		Tax: "(V) TA-1",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE B",
		Asignatura: "(Virtual) Deontología Periodística",
		UC: 4,
		Tax: "(V) TA-1",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE B",
		Asignatura: "Periodismo Transmedia",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE B",
		Asignatura: "(Virtual) Periodismo Transmedia",
		UC: 5,
		Tax: "(V) TA-2",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE B",
		Asignatura: "Periodismo de Investigación",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE B",
		Asignatura: "Electiva Presencial",
		UC: 3,
		Tax: "TA-4",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE B",
		Asignatura: "Electiva Virtual",
		UC: 3,
		Tax: "TA-4 (V)",
	},
	{
		Semestre: "CONCENTRACIÓN PERIODISMO SEMESTRE B",
		Asignatura: "Trabajo Final de la Concentración Periodismo",
		UC: 6,
		Tax: "TA-9",
	},
];

var comunicacionsocial = [
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Comunicación Audiovisual",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Comunicación 360",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Comunicación Periodística",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Comunicación Oral ",
		UC: 4,
		Tax: "TA-8",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: " Fundamentos de Gramática",
		UC: 5,
		Tax: "TA-6",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Competencia Textual en Español",
		UC: 5,
		Tax: "TA-6",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso I",
		UC: 3,
		Tax: "TA-1",
	},

	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Producción de Contenidos para Redes Sociales",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Locución",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Fotografía",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Comunicación Gráfica",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Comunicación Escrita I ",
		UC: 4,
		Tax: "TA-8",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Comprensión de Textos en Inglés",
		UC: 5,
		Tax: "TA-6",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso II",
		UC: 3,
		Tax: "TA-1",
	},

	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Producción de Contenidos para Medios",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Radio y Podcast",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: " Comunicación y Organización",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Teorías Sociales de la Comunicación ",
		UC: 5,
		Tax: "TA-1",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Comunicación Escrita II ",
		UC: 4,
		Tax: "TA-8",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Producción de Contenidos en Inglés ",
		UC: 5,
		Tax: "TA-6",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Ecología, Ambiente y Sustentabilidad",
		UC: 3,
		Tax: "TA-1",
	},

	{
		Semestre: "CUARTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Comunicaciones Integradas de Mercadeo ",
		UC: 4,
		Tax: "TA-2",
	},
	{
		Semestre: "CUARTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: " La Organización y sus Públicos ",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "CUARTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Estrategias Publicitarias",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "CUARTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Optimización y Mercadeo en Buscadores",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CUARTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Semiótica",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "CUARTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Semiótica (Virtual)",
		UC: 4,
		Tax: "TA-3 (V)",
	},
	{
		Semestre: "CUARTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Televisión y Streaming",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CUARTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Comunicación Escénica ",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "CUARTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Ética de la Comunicación Social ",
		UC: 4,
		Tax: "TA-1",
	},

	{
		Semestre: "QUINTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Analítica Web",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "QUINTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Diseño y Experiencia de Usuario",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "QUINTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Narrativas Digitales",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "QUINTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Campañas Publicitarias",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "QUINTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Gestión de Eventos",
		UC: 4,
		Tax: "TA-8",
	},
	{
		Semestre: "QUINTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Régimen Jurídico de la Comunicación ",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "QUINTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Innovación y Emprendimiento ",
		UC: 3,
		Tax: "TA-1",
	},
	{
		Semestre: "QUINTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Innovación y Emprendimiento (virtual)",
		UC: 3,
		Tax: "TA-1 (V)",
	},

	{
		Semestre: "SEXTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Métodos de Investigación de Mercados",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "SEXTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Outbound Marketing",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "SEXTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Comportamiento Empresarial Responsable",
		UC: 3,
		Tax: "TA-1",
	},
	{
		Semestre: "SEXTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Comportamiento Empresarial Responsable (virtual)",
		UC: 3,
		Tax: "TA-1 (V)",
	},
	{
		Semestre: "SEXTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Mercadeo Digital",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "SEXTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Cultura y Posmodernidad",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "SEXTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Cultura y Posmodernidad (virtual)",
		UC: 4,
		Tax: "TA-1 (V)",
	},
	{
		Semestre: "SEXTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Literatura y Comunicación ",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SEXTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Arte y Comunicación ",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SEXTO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Electiva",
		UC: 3,
		Tax: "TA-4",
	},

	{
		Semestre: "SÉPTIMO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Estrategias en el Punto de Venta y Canales de Comercialización",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Mercadeo Especializado",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Manejo de Crisis",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Estrategias y Políticas Comunicacionales",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Historia Contemporánea de Venezuela en los Medios",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Economía y Finanzas",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Sociología Política ",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Portafolio Profesional I",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Electiva",
		UC: 3,
		Tax: "TA-4",
	},

	{
		Semestre: "OCTAVO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Formación de Voceros",
		UC: 4,
		Tax: "TA-8",
	},
	{
		Semestre: "OCTAVO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Gestión Estratégica de la Publicidad",
		UC: 5,
		Tax: "TA-3",
	},
	{
		Semestre: "OCTAVO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Neuromarketing",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "OCTAVO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Psicología Social",
		UC: 3,
		Tax: "TA-1",
	},
	{
		Semestre: "OCTAVO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Opinión Pública",
		UC: 5,
		Tax: "TA-1",
	},
	{
		Semestre: "OCTAVO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Gerencia de Proyectos Comunicacionales",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "OCTAVO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Portafolio Profesional II ",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "OCTAVO SEMESTRE -  COMUNICACIONES INTEGRADAS DE MERCADEO",
		Asignatura: "Electiva",
		UC: 3,
		Tax: "TA-4",
	},

	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "Presentación y Narración de Noticias",
		UC: 4,
		Tax: "TA-8",
	},
	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "Periodismo",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "Procesos Editoriales",
		UC: 5,
		Tax: "TA-2",
	},
	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "Procesos Editoriales (virtual)",
		UC: 5,
		Tax: "TA-2 (V)",
	},
	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "La Organización y sus Públicos",
		UC: 4,
		Tax: "TA-2",
	},
	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "Semiótica",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "Semiótica (virtual)",
		UC: 4,
		Tax: "TA-3 (V)",
	},
	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "Televisión y Streaming",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "Comunicación Escénica",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "Ética de la Comunicación Social",
		UC: 4,
		Tax: "TA-1",
	},

	{
		Semestre: "CUARTO SEMESTRE - PERIODISMO",
		Asignatura: "Ética de la Comunicación Social",
		UC: 4,
		Tax: "TA-1",
	},

	{
		Semestre: "QUINTO SEMESTRE - PERIODISMO",
		Asignatura: "Fotografía Periodística",
		UC: 5,
		Tax: "TA-8",
	},
	{
		Semestre: "QUINTO SEMESTRE - PERIODISMO",
		Asignatura: "Producción de Contenidos Editoriales",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "QUINTO SEMESTRE - PERIODISMO",
		Asignatura: "Periodismo Radiofónico",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "QUINTO SEMESTRE - PERIODISMO",
		Asignatura: "Periodismo Televisivo",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "QUINTO SEMESTRE - PERIODISMO",
		Asignatura: "Gestión de Eventos",
		UC: 4,
		Tax: "TA-8",
	},
	{
		Semestre: "QUINTO SEMESTRE - PERIODISMO",
		Asignatura: "Régimen Jurídico de la Comunicación",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "QUINTO SEMESTRE - PERIODISMO",
		Asignatura: "Innovación y Emprendimiento",
		UC: 3,
		Tax: "TA-1",
	},
	{
		Semestre: "QUINTO SEMESTRE - PERIODISMO",
		Asignatura: "Innovación y Emprendimiento (virtual)",
		UC: 3,
		Tax: "TA-1 (V)",
	},

	{
		Semestre: "SEXTO SEMESTRE - PERIODISMO",
		Asignatura: "Periodismo Internacional",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SEXTO SEMESTRE - PERIODISMO",
		Asignatura: "Métodos de Investigación Periodística",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "SEXTO SEMESTRE - PERIODISMO",
		Asignatura: "Entrevista Periodística",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "SEXTO SEMESTRE - PERIODISMO",
		Asignatura: "Periodismo Transmedia",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "SEXTO SEMESTRE - PERIODISMO",
		Asignatura: "Periodismo Transmedia (virtual)",
		UC: 5,
		Tax: "TA-4 (V)",
	},
	{
		Semestre: "SEXTO SEMESTRE - PERIODISMO",
		Asignatura: "Cultura y Posmodernidad",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SEXTO SEMESTRE - PERIODISMO",
		Asignatura: "Cultura y Posmodernidad (virtual)",
		UC: 4,
		Tax: "TA-3 (V)",
	},
	{
		Semestre: "SEXTO SEMESTRE - PERIODISMO",
		Asignatura: "Literatura y Comunicación",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SEXTO SEMESTRE - PERIODISMO",
		Asignatura: "Arte y Comunicación",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SEXTO SEMESTRE - PERIODISMO",
		Asignatura: "Electiva",
		UC: 3,
		Tax: "TA-4",
	},

	{
		Semestre: "SÉPTIMO SEMESTRE - PERIODISMO",
		Asignatura: "Géneros Interpretativos",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - PERIODISMO",
		Asignatura: "Corresponsalía",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - PERIODISMO",
		Asignatura: "Gerencia de Medios",
		UC: 5,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - PERIODISMO",
		Asignatura: "Estrategias y Políticas Comunicacionales",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - PERIODISMO",
		Asignatura: "Historia Contemporánea de Venezuela en los Medios",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - PERIODISMO",
		Asignatura: "Economía y Finanzas",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - PERIODISMO",
		Asignatura: "Sociología Política",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - PERIODISMO",
		Asignatura: "Portafolio Profesional I",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - PERIODISMO",
		Asignatura: "Electiva",
		UC: 3,
		Tax: "TA-4",
	},

	{
		Semestre: "OCTAVO SEMESTRE - PERIODISMO",
		Asignatura: "Periodismo de Investigación",
		UC: 5,
		Tax: "TA-3",
	},
	{
		Semestre: "OCTAVO SEMESTRE - PERIODISMO",
		Asignatura: "Documental",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "OCTAVO SEMESTRE - PERIODISMO",
		Asignatura: "Discurso Periodístico",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "OCTAVO SEMESTRE - PERIODISMO",
		Asignatura: "Psicología Social",
		UC: 3,
		Tax: "TA-1",
	},
	{
		Semestre: "OCTAVO SEMESTRE - PERIODISMO",
		Asignatura: "Opinión Pública",
		UC: 5,
		Tax: "TA-1",
	},
	{
		Semestre: "OCTAVO SEMESTRE - PERIODISMO",
		Asignatura: "Gerencia de Proyectos Comunicacionales",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "OCTAVO SEMESTRE - PERIODISMO",
		Asignatura: "Portafolio Profesional II",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "OCTAVO SEMESTRE - PERIODISMO",
		Asignatura: "Electiva",
		UC: 3,
		Tax: "TA-4",
	},

	{
		Semestre: "CUARTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Producción Audiovisual",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "CUARTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Edición",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CUARTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Sonido",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CUARTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Taller de Cámara e Iluminación",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "CUARTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Semiótica",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "CUARTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Semiótica (virtual)",
		UC: 4,
		Tax: "TA-3 (V)",
	},
	{
		Semestre: "CUARTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Televisión y Streaming",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "CUARTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Comunicación Escénica",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "CUARTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Ética de la Comunicación Social",
		UC: 4,
		Tax: "TA-1",
	},

	{
		Semestre: "QUINTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Fundamentos de Guion",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "QUINTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Producción Cinematográfica",
		UC: 5,
		Tax: "TA-9",
	},
	{
		Semestre: "QUINTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Videografía",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "QUINTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Taller de Escenografía y Caracterización",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "QUINTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Gestión de Eventos",
		UC: 4,
		Tax: "TA-8",
	},
	{
		Semestre: "QUINTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Régimen Jurídico de la Comunicación",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "QUINTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Innovación y Emprendimiento",
		UC: 3,
		Tax: "TA-1",
	},
	{
		Semestre: "QUINTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Innovación y Emprendimiento (virtual)",
		UC: 3,
		Tax: "TA-1 (V)",
	},

	{
		Semestre: "SEXTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Teoría de la Imagen",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SEXTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Guion I",
		UC: 5,
		Tax: "TA-9",
	},
	{
		Semestre: "SEXTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Dirección de Arte",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "SEXTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Métodos de Investigación Audiovisual",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SEXTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Cultura y Posmodernidad",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "SEXTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Literatura y Comunicación",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SEXTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Arte y Comunicación",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SEXTO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Electiva",
		UC: 3,
		Tax: "TA-4",
	},

	{
		Semestre: "SÉPTIMO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Guion II",
		UC: 5,
		Tax: "TA-9",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Dirección Audiovisual",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Dirección de Fotografía",
		UC: 4,
		Tax: "TA-9",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Estrategias y Políticas Comunicacionales",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Historia Contemporánea de Venezuela en los Medios",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Economía y Finanzas",
		UC: 4,
		Tax: "TA-3",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Sociología Política",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Portafolio Profesional I",
		UC: 2,
		Tax: "TA-1",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Electiva",
		UC: 3,
		Tax: "TA-4",
	},

	{
		Semestre: "OCTAVO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Realización Cinematográfica",
		UC: 5,
		Tax: "TA-9",
	},
	{
		Semestre: "OCTAVO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Documental",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "OCTAVO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Gerencia de Medios Audiovisuales",
		UC: 4,
		Tax: "TA-4",
	},
	{
		Semestre: "OCTAVO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Psicología Social",
		UC: 3,
		Tax: "TA-1",
	},
	{
		Semestre: "OCTAVO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Opinión Pública",
		UC: 5,
		Tax: "TA-1",
	},
	{
		Semestre: "OCTAVO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Gerencia de Proyectos Comunicacionales",
		UC: 5,
		Tax: "TA-4",
	},
	{
		Semestre: "OCTAVO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Portafolio Profesional II",
		UC: 3,
		Tax: "TA-9",
	},
	{
		Semestre: "OCTAVO SEMESTRE - COMUNICACIÓN AUDIOVISUAL",
		Asignatura: "Electiva",
		UC: 3,
		Tax: "TA-4",
	},
];
