var contaduria = [
    {
        Semestre: "PRIMER SEMESTRE",
        Asignatura: "Comprensión Lectora y Redacción",
        UC: 5,
        Tax: "TA‐6",
    },
    { Semestre: "PRIMER SEMESTRE", Asignatura: "Matemáticas I", UC: 8, Tax: "TA‐6" },
    { Semestre: "PRIMER SEMESTRE", Asignatura: "Estadística I", UC: 5, Tax: "TA‐5" },
    { Semestre: "PRIMER SEMESTRE", Asignatura: "Lógica", UC: 3, Tax: "TA‐5" },
    {
        Semestre: "PRIMER SEMESTRE",
        Asignatura: "Identidad, Liderazgo y Compromiso I",
        UC: 3,
        Tax: "TA‐1",
    },
    { Semestre: "PRIMER SEMESTRE", Asignatura: "Teoría Contable", UC: 5, Tax: "TA‐1" },
    { Semestre: "SEGUNDO SEMESTRE", Asignatura: "Microeconomía I", UC: 7, Tax: "TA‐1" },
    { Semestre: "SEGUNDO SEMESTRE", Asignatura: "Cálculo", UC: 6, Tax: "TA‐6" },
    {
        Semestre: "SEGUNDO SEMESTRE",
        Asignatura: "Historia Económica Empresarial",
        UC: 3,
        Tax: "TA‐1",
    },
    { Semestre: "SEGUNDO SEMESTRE", Asignatura: "Estadística Aplicada", UC: 5, Tax: "TA‐5" },
    {
        Semestre: "SEGUNDO SEMESTRE",
        Asignatura: "Identidad, Liderazgo y Compromiso II",
        UC: 3,
        Tax: "TA‐1",
    },
    { Semestre: "SEGUNDO SEMESTRE", Asignatura: "Contabilidad I", UC: 7, Tax: "TA‐3" },
    { Semestre: "TERCER SEMESTRE", Asignatura: "Macroeconomía I", UC: 7, Tax: "TA‐1" },
    { Semestre: "TERCER SEMESTRE", Asignatura: "Matemáticas Aplicadas", UC: 5, Tax: "TA‐6" },
    {
        Semestre: "TERCER SEMESTRE",
        Asignatura: "(Virtual) Matemáticas Aplicadas",
        UC: 5,
        Tax: "(V) TA‐6",
    },
    { Semestre: "TERCER SEMESTRE", Asignatura: "Investigación Aplicada", UC: 4, Tax: "TA‐6" },
    { Semestre: "TERCER SEMESTRE", Asignatura: "Gerencia", UC: 6, Tax: "TA‐1" },
    { Semestre: "TERCER SEMESTRE", Asignatura: "Contabilidad II", UC: 7, Tax: "TA‐3" },
    {
        Semestre: "TERCER SEMESTRE",
        Asignatura: "(Virtual) Contabilidad II",
        UC: 7,
        Tax: "(V) TA‐3",
    },
    { Semestre: "CUARTO SEMESTRE", Asignatura: "Legislación Mercantil", UC: 3, Tax: "TA‐3" },
    { Semestre: "CUARTO SEMESTRE", Asignatura: "Matemáticas Financieras", UC: 4, Tax: "TA‐4" },
    {
        Semestre: "CUARTO SEMESTRE",
        Asignatura: "Ecología, Ambiente y Sustentabilidad",
        UC: 3,
        Tax: "TA‐1",
    },
    { Semestre: "CUARTO SEMESTRE", Asignatura: "Contabilidad Especializada", UC: 6, Tax: "TA‐3" },
    { Semestre: "CUARTO SEMESTRE", Asignatura: "Sistemas Contables", UC: 4, Tax: "TA‐9" },
    { Semestre: "CUARTO SEMESTRE", Asignatura: "Contabilidad III", UC: 8, Tax: "TA‐3" },
    {
        Semestre: "CUARTO SEMESTRE",
        Asignatura: "(Virtual) Contabilidad III",
        UC: 8,
        Tax: "(V) TA‐3",
    },
    { Semestre: "CUARTO SEMESTRE", Asignatura: "Innovación y Emprendimiento", UC: 3, Tax: "TA‐1" },
    { Semestre: "QUINTO SEMESTRE", Asignatura: "Derecho del Trabajo", UC: 6, Tax: "TA‐1" },
    {
        Semestre: "QUINTO SEMESTRE",
        Asignatura: "(Virtual) Derecho del Trabajo",
        UC: 6,
        Tax: "(V) TA‐1",
    },
    {
        Semestre: "QUINTO SEMESTRE",
        Asignatura: "Mercados e Instituciones Financieras",
        UC: 3,
        Tax: "TA‐1",
    },
    { Semestre: "QUINTO SEMESTRE", Asignatura: "Auditoria y Aseguramiento I", UC: 3, Tax: "TA‐1" },
    { Semestre: "QUINTO SEMESTRE", Asignatura: "Ética Profesional", UC: 3, Tax: "TA‐2" },
    { Semestre: "QUINTO SEMESTRE", Asignatura: "Costos I", UC: 4, Tax: "TA‐3" },
    { Semestre: "QUINTO SEMESTRE", Asignatura: "Contabilidad IV", UC: 8, Tax: "TA‐3" },
    { Semestre: "QUINTO SEMESTRE", Asignatura: "Inglés para los Negocios", UC: 3, Tax: "TA‐6" },
    {
        Semestre: "QUINTO SEMESTRE",
        Asignatura: "(Virtual) Inglés para los Negocios",
        UC: 3,
        Tax: "(V) TA‐6",
    },
    {
        Semestre: "QUINTO SEMESTRE",
        Asignatura: "Contabilidad IV",
        UC: 8,
        Tax: "TA‐3",
    },
    { Semestre: "SEXTO SEMESTRE", Asignatura: "Derecho Fiscal", UC: 3, Tax: "TA‐3" },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Responsabilidad Social Empresarial",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "(Virtual) Responsabilidad Social Empresarial",
        UC: 3,
        Tax: "(V) TA‐1",
    },
    { Semestre: "SEXTO SEMESTRE", Asignatura: "Finanzas I", UC: 6, Tax: "TA‐3" },
    { Semestre: "SEXTO SEMESTRE", Asignatura: "Auditoría y Aseguramiento II", UC: 3, Tax: "TA‐1" },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Informática Aplicada a los Negocios",
        UC: 3,
        Tax: "TA‐9",
    },
    { Semestre: "SEXTO SEMESTRE", Asignatura: "Costos II", UC: 4, Tax: "TA‐3" },
    { Semestre: "SEXTO SEMESTRE", Asignatura: "Contabilidad V", UC: 5, Tax: "TA‐3" },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Manejo de Habilidades Directivas",
        UC: 3,
        Tax: "TA‐6",
    },
    { Semestre: "SEXTO SEMESTRE", Asignatura: "Electiva", UC: 4, Tax: "TA‐8" },
    { Semestre: "SEXTO SEMESTRE", Asignatura: "(Virtual) Electiva", UC: 4, Tax: "(V) TA‐8" },
    { Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Derecho Tributario", UC: 6, Tax: "TA‐3" },
    {
        Semestre: "SÉPTIMO SEMESTRE",
        Asignatura: "Planificación Presupuestaria",
        UC: 5,
        Tax: "TA‐3",
    },
    {
        Semestre: "SÉPTIMO SEMESTRE",
        Asignatura: "(Virtual) Planificación Presupuestaria",
        UC: 5,
        Tax: "(V) TA‐3",
    },
    { Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Finanzas II", UC: 6, Tax: "TA‐3" },
    {
        Semestre: "SÉPTIMO SEMESTRE",
        Asignatura: "Auditoría y Aseguramiento III",
        UC: 3,
        Tax: "TA‐1",
    },
    { Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Tributación Municipal", UC: 3, Tax: "TA‐3" },
    { Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Electiva", UC: 4, Tax: "TA‐8" },
    { Semestre: "SÉPTIMO SEMESTRE", Asignatura: "(Virtual) Electiva", UC: 4, Tax: "(V) TA‐8" },
    { Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Costos III", UC: 4, Tax: "TA‐3" },
    { Semestre: "OCTAVO SEMESTRE", Asignatura: "Gerencia Tributaria", UC: 3, Tax: "TA‐3" },
    { Semestre: "OCTAVO SEMESTRE", Asignatura: "Trading", UC: 3, Tax: "TA‐6" },
    { Semestre: "OCTAVO SEMESTRE", Asignatura: "Control de Gestión", UC: 4, Tax: "TA‐3" },
    {
        Semestre: "OCTAVO SEMESTRE",
        Asignatura: "(Virtual) Control de Gestión",
        UC: 4,
        Tax: "(V) TA‐3",
    },
    { Semestre: "OCTAVO SEMESTRE", Asignatura: "Finanzas III", UC: 6, Tax: "TA‐3" },
    {
        Semestre: "OCTAVO SEMESTRE",
        Asignatura: "Auditoría y Aseguramiento IV",
        UC: 3,
        Tax: "TA‐1",
    },
    { Semestre: "OCTAVO SEMESTRE", Asignatura: "Electiva", UC: 4, Tax: "TA‐8" },
    { Semestre: "OCTAVO SEMESTRE", Asignatura: "(Virtual) Electiva", UC: 4, Tax: "(V) TA‐8" },
    {
        Semestre: "OCTAVO SEMESTRE",
        Asignatura: "Análisis de Estados Financieros",
        UC: 4,
        Tax: "TA‐4",
    },
    { Semestre: "OCTAVO SEMESTRE", Asignatura: "Auditoría Interna", UC: 3, Tax: "TA‐3" },
    { Semestre: "OCTAVO SEMESTRE", Asignatura: "Pasantía", UC: 3, Tax: "TA‐1" },
];
