var derecho = [
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Comprensión Lectora y Redacción",
		UC: 3,
		Tax: "TA‐8",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Orígenes del Derecho y Evolución Posterior",
		UC: 3,
		Tax: "TA‐1",
	},
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Teoría General del Derecho I", UC: 6, Tax: "TA‐1" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Lógica I", UC: 3, Tax: "TA‐5" },
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura:
			"Derecho Constitucional General I: Teoría de la Constitución y Teoría del Estado",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso I",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Derecho de las Personas: Parte General",
		UC: 5,
		Tax: "TA‐1",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso II",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Redacción de Textos Jurídicos",
		UC: 2,
		Tax: "TA‐8",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Codificación y Familias del Derecho",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Teoría General del Derecho II",
		UC: 6,
		Tax: "TA‐1",
	},
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Lógica II", UC: 3, Tax: "TA‐5" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "(Virtual) Lógica II", UC: 3, Tax: "(V) TA‐5" },
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura:
			"Derecho Constitucional General II: Sistema Político, Sistema de Gobierno y Forma de Estado",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Derecho de Personas: Parte Especial",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Teoría Política",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Metodología de la Investigación Jurídica",
		UC: 3,
		Tax: "TA‐8",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Instituciones Jurídicas Romanas I",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Fundamentos del Derecho Penal y de la Pena",
		UC: 5,
		Tax: "TA‐1",
	},
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Teoría General del Proceso I", UC: 5, Tax: "TA‐1" },
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Derecho Constitucional Venezolano I: Historia y Parte Dogmática",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Derecho de Bienes y Derechos Reales: Parte General",
		UC: 5,
		Tax: "TA‐1",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Seminario", UC: 3, Tax: "TA‐8" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Instituciones Jurídicas Romanas II",
		UC: 4,
		Tax: "TA‐1",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Teoría del Delito", UC: 5, Tax: "TA‐3" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Teoría General del Proceso II",
		UC: 5,
		Tax: "TA‐1",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Derecho Constitucional Venezolano II: Parte Orgánica y Garantías",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Derecho Internacional Público",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Ecología, Ambiente y Sustentabilidad",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Derecho de Bienes y Derechos Reales: Parte Especial",
		UC: 5,
		Tax: "TA‐1",
	},
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Inglés Jurídico I", UC: 3, Tax: "TA‐6" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Oratoria", UC: 2, Tax: "TA‐8" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Filosofía del Derecho I", UC: 4, Tax: "TA‐1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Delitos Especiales", UC: 4, Tax: "TA‐1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Derecho Procesal Civil I", UC: 4, Tax: "TA‐3" },
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Fundamentos de Derecho Administrativo",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Instituciones del Derecho Internacional Público (Presencial)",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Instituciones del Derecho Internacional Público (Virtual)",
		UC: 4,
		Tax: " (V)TA‐1",
	},
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Criminología", UC: 3, Tax: "TA‐3" },
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Teoría General de las Obligaciones",
		UC: 6,
		Tax: "TA‐1",
	},
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Inglés Jurídico II", UC: 3, Tax: "(SP) TA‐6" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Filosofía del Derecho II", UC: 4, Tax: "TA‐1" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Teoría y Política Económica", UC: 4, Tax: "TA‐1" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "(SP) Teoría y Política Económica",
		UC: 4,
		Tax: "(SP) TA‐1",
	},
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Ética", UC: 3, Tax: "TA‐1" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Derecho Penal Económico", UC: 4, Tax: "TA‐1" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Derecho Procesal Civil II", UC: 4, Tax: "TA‐3" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Teoría del Acto Administrativo y Procedimiento Administrativo",
		UC: 4,
		Tax: "TA‐1",
	},
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Derechos Humanos", UC: 3, Tax: "TA‐3" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Fuentes de las Obligaciones", UC: 6, Tax: "TA‐1" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Innovación y Emprendimiento", UC: 3, Tax: "TA‐1" },

	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Argumentación Jurídica", UC: 3, Tax: "TA‐4" },
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "(Virtual) Argumentación Jurídica",
		UC: 3,
		Tax: "(V) TA‐4",
	},
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Sociología Jurídica", UC: 3, Tax: "TA‐3" },
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Resolución Alternativa de Conflictos",
		UC: 3,
		Tax: "TA‐4",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Fundamentos y sujetos del Derecho del Trabajo",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Teoría de la Actividad Administrativa",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Fundamentos de Derecho Mercantil",
		UC: 4,
		Tax: "TA‐1",
	},
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Derecho de Familia", UC: 4, Tax: "TA‐1" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Contratos Especiales I", UC: 7, Tax: "TA‐1" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Arbitraje", UC: 3, Tax: "TA‐3" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Derecho Procesal Penal I", UC: 5, Tax: "TA‐3" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Teoría General de la Prueba", UC: 5, Tax: "TA‐1" },
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Derecho Individual del Trabajo",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Contratos Administrativos y Responsabilidad de la Administración Pública",
		UC: 4,
		Tax: "TA‐1",
	},
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Derecho de Sociedades", UC: 4, Tax: "TA‐1" },
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Contratos Especiales II y Derecho de Garantías",
		UC: 7,
		Tax: "TA‐1",
	},
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Electiva", UC: 3, Tax: "TA‐5" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "(SP) Electiva", UC: 3, Tax: "(SP) TA‐5" },
	{ Semestre: "NOVENO SEMESTRE", Asignatura: "Derecho Procesal Penal II", UC: 5, Tax: "TA‐3" },
	{ Semestre: "NOVENO SEMESTRE", Asignatura: "Pruebas en el Proceso", UC: 4, Tax: "TA‐3" },
	{
		Semestre: "NOVENO SEMESTRE",
		Asignatura: "Derecho Colectivo del Trabajo",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "NOVENO SEMESTRE",
		Asignatura: "Derecho Tributario: Parte General",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "NOVENO SEMESTRE",
		Asignatura: "Derecho Procesal Constitucional",
		UC: 4,
		Tax: "TA‐3",
	},
	{
		Semestre: "NOVENO SEMESTRE",
		Asignatura: "Derecho Internacional Privado",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "NOVENO SEMESTRE",
		Asignatura: "Contratos Mercantiles y Títulos Valores",
		UC: 4,
		Tax: "TA‐1",
	},
	{ Semestre: "NOVENO SEMESTRE", Asignatura: "Electiva", UC: 3, Tax: "TA‐5" },
	{ Semestre: "NOVENO SEMESTRE", Asignatura: "(SP) Electiva", UC: 3, Tax: "(SP) TA‐5" },
	{ Semestre: "NOVENO SEMESTRE", Asignatura: "Clínica Jurídica I", UC: 2, Tax: "TA‐9" },
	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Prácticas", UC: 2, Tax: "TA‐8" },
	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Casación", UC: 4, Tax: "TA‐1" },
	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Derecho Procesal del Trabajo", UC: 3, Tax: "TA‐3" },
	{
		Semestre: "DECIMO SEMESTRE",
		Asignatura: "Derecho Tributario: Parte Especial",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "DECIMO SEMESTRE",
		Asignatura: "Derecho Procesal Administrativo",
		UC: 4,
		Tax: "TA‐3",
	},
	{
		Semestre: "DECIMO SEMESTRE",
		Asignatura: "Derecho Procesal Civil Internacional",
		UC: 4,
		Tax: "TA‐3",
	},
	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Derecho Concursal", UC: 4, Tax: "TA‐1" },
	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Derecho de Sucesiones", UC: 4, Tax: "TA‐1" },
	{ Semestre: "DECIMO SEMESTRE", Asignatura: "Clínica Jurídica II", UC: 2, Tax: "TA‐9" },
];
