var letras = [
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso I",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Competencia Textual en Español",
		UC: 5,
		Tax: "TA-6",
	},
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Morfosintaxis I", UC: 5, Tax: "TA‐4" },
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Introducción a los Estudios Literarios",
		UC: 5,
		Tax: "TA‐1",
	},
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Lingüística I", UC: 5, Tax: "TA‐1" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Historia del Arte I", UC: 5, Tax: "TA‐1" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Metodología", UC: 5, Tax: "TA‐8" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Cultura Occidental I", UC: 5, Tax: "TA‐1" },
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso II",
		UC: 3,
		Tax: "TA‐1",
	},
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Morfosintaxis II", UC: 3, Tax: "TA‐4" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Historia del Arte II", UC: 5, Tax: "TA‐1" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Teoría Literaria I", UC: 5, Tax: "TA‐1" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Literatura Clásica", UC: 5, Tax: "TA‐1" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Lingüística II", UC: 5, Tax: "TA‐1" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Redacción y Estilo", UC: 5, Tax: "TA‐4" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Cultura Occidental II", UC: 5, Tax: "TA‐1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Literatura Latinoamericana I", UC: 5, Tax: "TA‐1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Literatura Venezolana I", UC: 5, Tax: "TA‐1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Literatura Medieval", UC: 5, Tax: "TA‐1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Teoría Literaria II", UC: 5, Tax: "TA‐1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Lingüística III", UC: 5, Tax: "TA‐1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Arte Latinoamericano", UC: 5, Tax: "TA‐1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Latín I", UC: 5, Tax: "TA‐4" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "(SP) Latín I", UC: 5, Tax: "(SP) TA‐4" },
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Ecologia, Ambiente y Sustentabilidad",
		UC: 3,
		Tax: "TA‐1",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Teoría Literaria III", UC: 5, Tax: "TA‐1" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Literatura Latinoamericana II",
		UC: 5,
		Tax: "TA‐1",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Literatura Venezolana II", UC: 5, Tax: "TA‐1" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Literatura del Renacimiento y Barroco",
		UC: 5,
		Tax: "TA‐1",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Literatura Española del Siglo de Oro",
		UC: 5,
		Tax: "TA‐1",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Latín II", UC: 5, Tax: "TA‐4" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "(Virtual) Latín II", UC: 5, Tax: "(V) TA‐4" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Lingüística IV", UC: 5, Tax: "TA‐1" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Seminario", UC: 3, Tax: "TA‐2" },
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Literatura Latinoamericana III",
		UC: 5,
		Tax: "TA‐1",
	},
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Literatura Venezolana III", UC: 5, Tax: "TA‐1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Literatura del Romanticismo", UC: 5, Tax: "TA‐1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Teoría literaria IV", UC: 5, Tax: "TA‐1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Lingüística V", UC: 5, Tax: "TA‐1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Seminario", UC: 3, Tax: "TA‐2" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "(Virtual) Seminario", UC: 3, Tax: "(V) TA‐2" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Historia del Pensamiento ", UC: 5, Tax: "TA‐1" },
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Taller de Escritura Creativa I",
		UC: 2,
		Tax: "TA‐8",
	},
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Literatura Realista", UC: 5, Tax: "TA‐1" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Literatura Venezolana IV", UC: 5, Tax: "TA‐1" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Proyecto de Investigación", UC: 3, Tax: "TA‐6" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Seminario", UC: 3, Tax: "TA‐2" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "(Virtual) Seminario", UC: 3, Tax: "(V) TA‐2" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Taller de Escritura Creativa II",
		UC: 2,
		Tax: "TA‐8",
	},
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Producción y Edición de Libros",
		UC: 5,
		Tax: "TA‐5",
	},
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Producción de Medios Digitales",
		UC: 5,
		Tax: "TA‐9",
	},
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Inglés I",
		UC: 5,
		Tax: "TA‐6",
	},
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Literatura Latinoamericana IV ",
		UC: 5,
		Tax: "TA‐1",
	},
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Poesía Moderna", UC: 5, Tax: "TA‐1" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Narrativa Moderna", UC: 5, Tax: "TA‐1" },
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Seminario de Trabajo de Grado I",
		UC: 3,
		Tax: "TA‐9",
	},
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Electiva", UC: 3, Tax: "TA‐4" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "(Virtual) Electiva", UC: 3, Tax: "(V) TA‐4" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Teatro Contemporáneo", UC: 5, Tax: "TA‐1" },
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Gestión de Proyectos Culturales",
		UC: 5,
		Tax: "TA‐5",
	},
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Inglés II", UC: 4, Tax: "TA‐6" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Pasantía", UC: 0, UCE: 3, Tax: "TA‐7" },
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Seminario de Trabajo de Grado II",
		UC: 3,
		Tax: "TA‐9",
	},
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Electiva", UC: 3, Tax: "TA‐4" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "(Virtual) Electiva", UC: 3, Tax: "(V) TA‐4" },
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Seminario de Crítica e Investigación Literaria",
		UC: 3,
		Tax: "TA‐2",
	},
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Mercadeo Editorial", UC: 3, Tax: "TA‐5" },
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Diseño y Evaluación de Proyectos Culturales",
		UC: 5,
		Tax: "TA‐5",
	},
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Narrativa Norteamericana Contemporánea",
		UC: 5,
		Tax: "TA‐1",
	},
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Innovación y Emprendimiento", UC: 3, Tax: "TA‐1" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Trabajo de Grado", UC: 6, Tax: "TA‐1" },
];
