let minors = [
	{
		Semestre: "(MINOR) DERECHO INTERNACIONAL PÚBLICO",
		Asignatura: "Teoría General del Derecho II",
		UC: 6,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) DERECHO INTERNACIONAL PÚBLICO",
		Asignatura:
			"Derecho Constitucional General II: Sistema Político, Sistema de Gobierno y Forma de Estado",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) DERECHO INTERNACIONAL PÚBLICO",
		Asignatura: "Derecho Internacional Público",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) DERECHO INTERNACIONAL PÚBLICO",
		Asignatura: "Instituciones del Derecho Internacional Público",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) DERECHO INTERNACIONAL PÚBLICO",
		Asignatura: "(Virtual) Instituciones del Derecho Internacional Público",
		UC: 4,
		Tax: "(V) TA‐1",
	},
	{
		Semestre: "(MINOR) DERECHO INTERNACIONAL PÚBLICO",
		Asignatura: "Derechos Humanos",
		UC: 3,
		Tax: "TA‐3",
	},
	{
		Semestre: "(MINOR) GESTIÓN CULTURAL Y EDITORIAL",
		Asignatura: "Gestión de Proyectos Culturales",
		UC: 5,
		Tax: "TA‐5",
	},
	{
		Semestre: "(MINOR) GESTIÓN CULTURAL Y EDITORIAL",
		Asignatura: "Diseño y Evaluación de Proyectos Culturales",
		UC: 5,
		Tax: "TA‐5",
	},
	{
		Semestre: "(MINOR) GESTIÓN CULTURAL Y EDITORIAL",
		Asignatura: "Producción y Edición de Libros",
		UC: 5,
		Tax: "TA‐5",
	},
	{
		Semestre: "(MINOR) GESTIÓN CULTURAL Y EDITORIAL",
		Asignatura: "Producción de Medios Digitales",
		UC: 5,
		Tax: "TA‐9",
	},
	{
		Semestre: "(MINOR) GESTIÓN CULTURAL Y EDITORIAL",
		Asignatura: "Mercadeo Editorial",
		UC: 3,
		Tax: "TA‐5",
	},
	{
		Semestre: "(MINOR) ESCRITURA CREATIVA",
		Asignatura: "Redacción y Estilo",
		UC: 4,
		Tax: "TA‐4",
	},
	{
		Semestre: "(MINOR) ESCRITURA CREATIVA",
		Asignatura: "Taller de Escritura Creativa I",
		UC: 2,
		Tax: "TA‐8",
	},
	{
		Semestre: "(MINOR) ESCRITURA CREATIVA",
		Asignatura: "Taller de Escritura Creativa II",
		UC: 2,
		Tax: "TA‐8",
	},
	{
		Semestre: "(MINOR) ESCRITURA CREATIVA",
		Asignatura: "Producción de Medios Digitales",
		UC: 4,
		Tax: "TA‐9",
	},
	{
		Semestre: "(MINOR) ESCRITURA CREATIVA",
		Asignatura: "Introducción a los Estudios Literarios",
		UC: 6,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) ESCRITURA CREATIVA",
		Asignatura: "Narrativa Moderna",
		UC: 6,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) PSICOLOGÍA APLICADA A LA EDUCACIÓN",
		Asignatura: "Psicología General",
		UC: 6,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) PSICOLOGÍA APLICADA A LA EDUCACIÓN",
		Asignatura: "Desarrollo Humano",
		UC: 6,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) PSICOLOGÍA APLICADA A LA EDUCACIÓN",
		Asignatura: "Teorías y Modelos del Aprendizaje",
		UC: 4,
		Tax: "(SP) TA‐3",
	},
	{
		Semestre: "(MINOR) PSICOLOGÍA APLICADA A LA EDUCACIÓN",
		Asignatura: "Asesoramiento",
		UC: 5,
		Tax: "(SP) TA‐3",
	},
	{
		Semestre: "(MINOR) PSICOLOGÍA APLICADA A LA EDUCACIÓN",
		Asignatura: "Estrategias para la Diversidad",
		UC: 5,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) TECNOLOGÍA EDUCATIVA",
		Asignatura: "Teorías y Modelos del Aprendizaje",
		UC: 4,
		Tax: "(SP) TA‐3",
	},
	{
		Semestre: "(MINOR) TECNOLOGÍA EDUCATIVA",
		Asignatura: "Manejo de Medios Digitales",
		UC: 3,
		Tax: "TA‐9",
	},
	{
		Semestre: "(MINOR) TECNOLOGÍA EDUCATIVA",
		Asignatura: "Producción de Medios Digitales",
		UC: 3,
		Tax: "(SP) TA‐9",
	},
	{
		Semestre: "(MINOR) TECNOLOGÍA EDUCATIVA",
		Asignatura: "(VIRTUAL) Gestión de Entornos Virtuales",
		UC: 3,
		Tax: "(V) TA‐9",
	},
	{
		Semestre: "(MINOR) TECNOLOGÍA EDUCATIVA",
		Asignatura: "Innovación y Emprendimiento",
		UC: 3,
		Tax: "TA‐4",
	},

	{
		Semestre: "(MINOR) VOCERÍA",
		Asignatura: "Comunicación Oral",
		UC: 4,
		Tax: "TA‐8",
	},
	{
		Semestre: "(MINOR) VOCERÍA",
		Asignatura: "Opinión Pública",
		UC: 6,
		Tax: "TA‐2",
	},
	{
		Semestre: "(MINOR) VOCERÍA",
		Asignatura: "Régimen Jurídico de la Comunicación",
		UC: 6,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) VOCERÍA",
		Asignatura: "Teorías Administrativas y de la Organización",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) VOCERÍA",
		Asignatura: "Comunicaciones Internas y Externas",
		UC: 6,
		Tax: "TA‐2",
	},
	{
		Semestre: "(MINOR) VOCERÍA",
		Asignatura: "Vocería y Telegenia",
		UC: 4,
		Tax: "TA‐8",
	},
	{
		Semestre: "(MINOR) COMUNICACIÓN PARA EL MERCADEO",
		Asignatura: "Mercadeo",
		UC: 5,
		Tax: "TA‐4",
	},
	{
		Semestre: "(MINOR) COMUNICACIÓN PARA EL MERCADEO",
		Asignatura: "Fundamentos de Comunicaciones Integradas de Mercadeo",
		UC: 5,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) COMUNICACIÓN PARA EL MERCADEO",
		Asignatura: "Mercadeo Digital",
		UC: 5,
		Tax: "(SP) TA‐2",
	},
	{
		Semestre: "(MINOR) COMUNICACIÓN PARA EL MERCADEO",
		Asignatura: "Publicidad",
		UC: 5,
		Tax: "TA‐2",
	},
	{
		Semestre: "(MINOR) COMUNICACIÓN PARA EL MERCADEO",
		Asignatura: "Investigación de Mercados",
		UC: 5,
		Tax: "TA‐2",
	},
	{
		Semestre: "(MINOR) COMUNICACIÓN PARA EL MERCADEO",
		Asignatura: "Mercadeo de Servicios",
		UC: 5,
		Tax: "TA‐2",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL CAMBIO PARA PROCESOS PRODUCTIVOS Y DE NEGOCIOS",
		Asignatura: "Diseño de Sistemas Productivos",
		UC: 5,
		Tax: "TA‐4",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL CAMBIO PARA PROCESOS PRODUCTIVOS Y DE NEGOCIOS",
		Asignatura: "(Virtual) Gestión de Empresas",
		UC: 4,
		Tax: "(V) TA‐8",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL CAMBIO PARA PROCESOS PRODUCTIVOS Y DE NEGOCIOS",
		Asignatura: "(Virtual) Gestión de la Calidad",
		UC: 5,
		Tax: "(V) TA‐8",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL CAMBIO PARA PROCESOS PRODUCTIVOS Y DE NEGOCIOS",
		Asignatura: "(Virtual) Gestión de Proyectos",
		UC: 5,
		Tax: "(V) TA‐8",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL CAMBIO PARA PROCESOS PRODUCTIVOS Y DE NEGOCIOS",
		Asignatura: "(Virtual) Gestión Logística",
		UC: 4,
		Tax: "(V) TA‐8",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL CAMBIO PARA PROCESOS PRODUCTIVOS Y DE NEGOCIOS",
		Asignatura: "(Virtual) Iniciativas Emprendedoras",
		UC: 4,
		Tax: "(V) TA‐8",
	},
	{
		Semestre: "(MINOR) ANÁLISIS SOCIO-POLÍTICO CASO VENEZUELA",
		Asignatura: "Filosofía Social y Política",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) ANÁLISIS SOCIO-POLÍTICO CASO VENEZUELA",
		Asignatura: "Teorías Políticas",
		UC: 5,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) ANÁLISIS SOCIO-POLÍTICO CASO VENEZUELA",
		Asignatura: "Sociología Política",
		UC: 5,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) ANÁLISIS SOCIO-POLÍTICO CASO VENEZUELA",
		Asignatura: "Cambio Social en Venezuela",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) ANÁLISIS SOCIO-POLÍTICO CASO VENEZUELA",
		Asignatura: "Políticas Públicas",
		UC: 5,
		Tax: "TA‐3",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL TALENTO HUMANO",
		Asignatura: "Gestión del Talento Humano",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL TALENTO HUMANO",
		Asignatura: "Comportamiento Organizacional",
		UC: 3,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL TALENTO HUMANO",
		Asignatura: "Captación del Talento",
		UC: 4,
		Tax: "TA‐3",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL TALENTO HUMANO",
		Asignatura: "Capacitación y Desarrollo del Talento",
		UC: 4,
		Tax: "TA‐3",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL TALENTO HUMANO",
		Asignatura: "Gestión del Desempeño",
		UC: 4,
		Tax: "TA‐3",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL TALENTO HUMANO",
		Asignatura: "(Virtual) Compensación del Trabajo I",
		UC: 4,
		Tax: "(V) TA‐3",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL TALENTO HUMANO",
		Asignatura: "Compensación del Trabajo I",
		UC: 4,
		Tax: "TA‐3",
	},
	{
		Semestre: "(MINOR) GESTIÓN DEL TALENTO HUMANO",
		Asignatura: "Planificación Estratégica de RRHH",
		UC: 4,
		Tax: "TA‐3",
	},
	{
		Semestre: "(MINOR) ECONOMÍA",
		Asignatura: "Microeconomía I",
		UC: 7,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) ECONOMÍA",
		Asignatura: "Macroeconomía I",
		UC: 7,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) ECONOMÍA",
		Asignatura: "Historia del Pensamiento Económico",
		UC: 5,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) ECONOMÍA",
		Asignatura: "Pensamiento Económico Venezolano",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) MARKETING",
		Asignatura: "Principios de Marketing",
		UC: 5,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) MARKETING",
		Asignatura: "Gerencia de Producto",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) MARKETING",
		Asignatura: "Comunicaciones Integradas de Marketing",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) MARKETING",
		Asignatura: "Trade Marketing",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) MARKETING",
		Asignatura: "Dirección Estratégica de Marketing",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) FINANZAS EMPRESARIALES",
		Asignatura: "Matemáticas Financieras",
		UC: 4,
		Tax: "TA‐4",
	},
	{
		Semestre: "(MINOR) FINANZAS EMPRESARIALES",
		Asignatura: "Mercados e Instituciones Financieras",
		UC: 4,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) FINANZAS EMPRESARIALES",
		Asignatura: "Gerencia Financiera",
		UC: 5,
		Tax: "TA‐4",
	},
	{
		Semestre: "(MINOR) FINANZAS EMPRESARIALES",
		Asignatura: "Finanzas Corporativas",
		UC: 5,
		Tax: "TA‐4",
	},
	{
		Semestre: "(MINOR) FINANZAS EMPRESARIALES",
		Asignatura: "Finanzas Internacionales",
		UC: 4,
		Tax: "TA‐3",
	},
	{
		Semestre: "(MINOR) FINANZAS EMPRESARIALES",
		Asignatura: "Trading",
		UC: 4,
		Tax: "TA‐6",
	},
	{
		Semestre: "(MINOR) ANÁLISIS CONTABLE",
		Asignatura: "Teoría Contable",
		UC: 5,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) ANÁLISIS CONTABLE",
		Asignatura: "Contabilidad I",
		UC: 7,
		Tax: "TA‐3",
	},
	{
		Semestre: "(MINOR) ANÁLISIS CONTABLE",
		Asignatura: "Contabilidad II",
		UC: 7,
		Tax: "TA‐3",
	},
	{
		Semestre: "(MINOR) ANÁLISIS CONTABLE",
		Asignatura: "Gerencia",
		UC: 6,
		Tax: "TA‐1",
	},
	{
		Semestre: "(MINOR) ANÁLISIS CONTABLE",
		Asignatura: "Sistemas Contables",
		UC: 4,
		Tax: "TA‐9",
	},
];
