var psicologianuevopensum = [
    {
        Semestre: "PRIMER SEMESTRE",
        Asignatura: "Comprensión y Producción de Textos Escritos",
        UC: 5,
        Tax: "TA‐6",
    },
    {
        Semestre: "PRIMER SEMESTRE",
        Asignatura: "Identidad, Liderazgo y Compromiso I",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "PRIMER SEMESTRE",
        Asignatura: "Historia y Fundamentos Filosóficos de la Psicología",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "PRIMER SEMESTRE",
        Asignatura: "Introducción al Estudio de la Psicología",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "PRIMER SEMESTRE",
        Asignatura: "Investigación Documental",
        UC: 2,
        Tax: "TA‐6",
    },
    {
        Semestre: "PRIMER SEMESTRE",
        Asignatura: "Cultura, Sociedad e Individuo",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "PRIMER SEMESTRE",
        Asignatura: "Matemática y Estadística",
        UC: 8,
        Tax: "TA‐5",
    },
    {
        Semestre: "SEGUNDO SEMESTRE",
        Asignatura: "Identidad, Liderazgo y Compromiso II",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEGUNDO SEMESTRE",
        Asignatura: "Psicobiología",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEGUNDO SEMESTRE",
        Asignatura: "Teorías y Sistemas en Psicología",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEGUNDO SEMESTRE",
        Asignatura: "Introducción a la Investigación",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEGUNDO SEMESTRE",
        Asignatura: "Psicología de la Sensopercepción y de la Atención",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEGUNDO SEMESTRE",
        Asignatura: "Psicología del Desarrollo de la Ñiñez",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEGUNDO SEMESTRE",
        Asignatura: "Estadística I",
        UC: 8,
        Tax: "TA‐5",
    },
    {
        Semestre: "TERCER SEMESTRE",
        Asignatura: "Psicología del Aprendizaje",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "TERCER SEMESTRE",
        Asignatura: "Psicología de la Motivación y de la Emoción",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "TERCER SEMESTRE",
        Asignatura: " Psicología del Desarrollo de la Adolescencia y de la Adultez",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "TERCER SEMESTRE",
        Asignatura: "Neurociencias I",
        UC: 5,
        Tax: "TA‐3",
    },
    {
        Semestre: "TERCER SEMESTRE",
        Asignatura: "Técnicas de Recolección de Información",
        UC: 5,
        Tax: "TA‐4",
    },
    {
        Semestre: "TERCER SEMESTRE",
        Asignatura: "Antropología Filosófica",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "TERCER SEMESTRE",
        Asignatura: "Estadística II",
        UC: 6,
        Tax: "TA‐5",
    },
    {
        Semestre: "CUARTO SEMESTRE",
        Asignatura: "Filosofía de la Ciencia ",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "CUARTO SEMESTRE",
        Asignatura: "Neurociencias II ",
        UC: 5,
        Tax: "TA‐3",
    },
    {
        Semestre: "CUARTO SEMESTRE",
        Asignatura: "Psicología de la Memoria ",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "CUARTO SEMESTRE",
        Asignatura: "Psicología de la Personalidad I",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "CUARTO SEMESTRE",
        Asignatura: "Investigación Cuantitativa No Experimental",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "CUARTO SEMESTRE",
        Asignatura: "Psicometría",
        UC: 8,
        Tax: "TA‐3",
    },
    {
        Semestre: "CUARTO SEMESTRE",
        Asignatura: "Ecología, Ambiente y Sustentabilidad",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "QUINTO SEMESTRE",
        Asignatura: "Procesos Cognitivos Superiores",
        UC: 8,
        Tax: "TA‐1",
    },
    {
        Semestre: "QUINTO SEMESTRE",
        Asignatura: "Psicología de la Personalidad II",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "QUINTO SEMESTRE",
        Asignatura: "Psicología Social I",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "QUINTO SEMESTRE",
        Asignatura: "Psicología Experimental",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "QUINTO SEMESTRE",
        Asignatura: "Investigación Cualitativa I ",
        UC: 5,
        Tax: "TA‐2",
    },
    {
        Semestre: "QUINTO SEMESTRE",
        Asignatura: "Neurociencias Cognitivas y Neuropsicología",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Psicología Social II",
        UC: 5,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Investigación Cualitativa II",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Gestión de Proyectos",
        UC: 5,
        Tax: "TA‐6",
    },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Psicopatología de la Niñez y de la Adolescencia",
        UC: 6,
        Tax: "TA‐1",
    },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Evaluación Psicológica I",
        UC: 7,
        Tax: "TA‐2",
    },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Prácticas de Psicología Experimental",
        UC: 2,
        Tax: "TA‐4",
    },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Electiva",
        UC: 3,
        Tax: "TA‐4",
    },
    {
        Semestre: "SEXTO SEMESTRE",
        Asignatura: "Electiva (Virtual)",
        UC: 3,
        Tax: "(V) TA‐4",
    },
    {
        Semestre: "SÉPTIMO SEMESTRE",
        Asignatura: "Psicología Clínica de la Niñez y de la Adolescencia",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "SÉPTIMO SEMESTRE",
        Asignatura: "Evaluación Psicológica II",
        UC: 7,
        Tax: "TA‐2",
    },
    {
        Semestre: "SÉPTIMO SEMESTRE",
        Asignatura: "Psicología Escolar",
        UC: 6,
        Tax: "TA‐1",
    },
    {
        Semestre: "SÉPTIMO SEMESTRE",
        Asignatura: "Psicología Industrial y Organizacional I",
        UC: 5,
        Tax: "TA‐4",
    },
    {
        Semestre: "SÉPTIMO SEMESTRE",
        Asignatura: "Electiva",
        UC: 3,
        Tax: "TA‐4",
    },
    {
        Semestre: "SÉPTIMO SEMESTRE",
        Asignatura: "Electiva (virtual)",
        UC: 3,
        Tax: "(V) TA‐4",
    },
    {
        Semestre: "SÉPTIMO SEMESTRE",
        Asignatura: "Innovación y Emprendimiento",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "OCTAVO SEMESTRE",
        Asignatura: "Evaluación Psicológica III",
        UC: 7,
        Tax: "TA‐2",
    },
    {
        Semestre: "OCTAVO SEMESTRE",
        Asignatura: "Trabajo de Grado I",
        UC: 4,
        Tax: "TA‐4",
    },
    {
        Semestre: "OCTAVO SEMESTRE",
        Asignatura: "Psicopatología de la Adultez",
        UC: 6,
        Tax: "TA‐1",
    },
    {
        Semestre: "OCTAVO SEMESTRE",
        Asignatura: "Asesoramiento Psicológico",
        UC: 6,
        Tax: "TA‐1",
    },
    {
        Semestre: "OCTAVO SEMESTRE",
        Asignatura: "Pasantías de Psicología Clínica de la Niñez y de la Adolescencia",
        UC: 6,
        Tax: "TA‐7",
    },
    {
        Semestre: "OCTAVO SEMESTRE",
        Asignatura: "Pasantías de Psicología Escolar I",
        UC: 6,
        Tax: "TA‐7",
    },
    {
        Semestre: "OCTAVO SEMESTRE",
        Asignatura: "Psicología Industrial y Organizacional II",
        UC: 5,
        Tax: "TA‐4",
    },
    {
        Semestre: "NOVENO SEMESTRE",
        Asignatura: "Trabajo de Grado II",
        UC: 4,
        Tax: "TA‐4",
    },
    {
        Semestre: "NOVENO SEMESTRE",
        Asignatura: "Trabajo de Grado II (Virtual)",
        UC: 4,
        Tax: "(V) TA‐1",
    },
    {
        Semestre: "NOVENO SEMESTRE",
        Asignatura: "Psicología Clínica de la Adultez",
        UC: 3,
        Tax: "TA‐1",
    },
    {
        Semestre: "NOVENO SEMESTRE",
        Asignatura: "Pasantías de Psicología Escolar II",
        UC: 6,
        Tax: "TA‐7",
    },
    {
        Semestre: "NOVENO SEMESTRE",
        Asignatura: "Pasantías en Asesoramiento Psicológico I",
        UC: 6,
        Tax: "TA‐7",
    },
    {
        Semestre: "NOVENO SEMESTRE",
        Asignatura: "Evaluación Psicológica IV",
        UC: 5,
        Tax: "TA‐2",
    },
    {
        Semestre: "NOVENO SEMESTRE",
        Asignatura: "Electiva",
        UC: 3,
        Tax: "TA‐4",
    },
    {
        Semestre: "NOVENO SEMESTRE",
        Asignatura: "Electiva (Virtual)",
        UC: 3,
        Tax: "(V) TA‐1",
    },
    {
        Semestre: "NOVENO SEMESTRE",
        Asignatura: "Electiva",
        UC: 3,
        Tax: "TA‐4",
    },
    {
        Semestre: "NOVENO SEMESTRE",
        Asignatura: "Electiva (Virtual)",
        UC: 3,
        Tax: "(V) TA‐1",
    },
    {
        Semestre: "DECIMO SEMESTRE",
        Asignatura: "Ética Profesional",
        UC: 2,
        Tax: "TA‐2",
    },
    {
        Semestre: "DECIMO SEMESTRE",
        Asignatura: "Crítica a los Sistemas Psicológicos ",
        UC: 2,
        Tax: "TA‐2",
    },
    {
        Semestre: "DECIMO SEMESTRE",
        Asignatura: "Trabajo de Grado III",
        UC: 4,
        Tax: "TA‐4",
    },
    {
        Semestre: "DECIMO SEMESTRE",
        Asignatura: "Trabajo de Grado III (Virtual)",
        UC: 4,
        Tax: "(V) TA‐1",
    },
    {
        Semestre: "DECIMO SEMESTRE",
        Asignatura: "Pasantías en Psicología Clínica de la Adultez",
        UC: 8,
        Tax: "TA‐7",
    },
    {
        Semestre: "DECIMO SEMESTRE",
        Asignatura: "Pasantías en Asesoramiento Psicológico II",
        UC: 6,
        Tax: "TA‐7",
    },
    {
        Semestre: "DECIMO SEMESTRE",
        Asignatura: "Electiva",
        UC: 3,
        Tax: "TA‐4",
    },
    {
        Semestre: "DECIMO SEMESTRE",
        Asignatura: "Electiva (Virtual)",
        UC: 3,
        Tax: "(V) TA‐1",
    },
];
