var psicologianuevopensum = [
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Competencia Textual en Español 1",
		UC: 3,
		Tax: "TA-6",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Fundamentos Epistemológicos y Antropológicos de la Psicología",
		UC: 2,
		Tax: "TA-1",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso I",
		UC: 1,
		Tax: "TA-1",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Introducción a la Investigación",
		UC: 2,
		Tax: "TA-1",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Introducción al Estudio de la Psicología",
		UC: 2,
		Tax: "TA-1",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Matemática y Probabilidad",
		UC: 4,
		Tax: "TA-5",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Estadística Descriptiva",
		UC: 4,
		Tax: "TA-5",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso II",
		UC: 1,
		Tax: "TA-1",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Investigación Documental",
		UC: 2,
		Tax: "TA-8",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Neuropsicobiología",
		UC: 2,
		Tax: "TA-3",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Psicología de la Sensopercepción y de la Atención",
		UC: 2,
		Tax: "TA-1",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Psicología del Desarrollo de la Niñez",
		UC: 2,
		Tax: "TA-1",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Teorías y Sistemas en Psicología",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Ecología, Ambiente y Sustentabilidad",
		UC: 1,
		Tax: "TA-1",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Estadística Inferencial",
		UC: 4,
		Tax: "TA-5",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Innovación y Emprendimiento",
		UC: 1,
		Tax: "TA-1",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Neurociencia Conductual",
		UC: 2,
		Tax: "TA-3",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Psicología de la Motivación y Emoción",
		UC: 2,
		Tax: "TA-3",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Psicología del Aprendizaje",
		UC: 2,
		Tax: "TA-3",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Psicología del Desarrollo de la Adolescencia y de la Adultez",
		UC: 2,
		Tax: "TA-3",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Investigación Cualitativa",
		UC: 2,
		Tax: "TA-3",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Investigación Cuantitativa No Experimental",
		UC: 2,
		Tax: "TA-1",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Neuropsicología y Neurociencias Cognitivas",
		UC: 2,
		Tax: "TA-3",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Psicología de la Memoria y de la Inteligencia",
		UC: 2,
		Tax: "TA-1",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Psicología del Pensamiento y Lenguaje",
		UC: 2,
		Tax: "TA-1",
	},
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Psicología Social",
		UC: 2,
		Tax: "TA-1",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Psicometría",
		UC: 2,
		Tax: "TA-3",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Evaluación Psicológica de la Niñez",
		UC: 2,
		Tax: "TA-8",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Psicología de Grupos",
		UC: 2,
		Tax: "TA-3",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Psicología de la Personalidad",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Psicología Experimental",
		UC: 2,
		Tax: "TA-5",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Psicología Social Aplicada",
		UC: 2,
		Tax: "TA-8",
	},
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Producción y Edición de Libros",
		UC: 3,
		Tax: "TA-6",
	},
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Proyectos de Investigación",
		UC: 2,
		Tax: "TA-6",
	},
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Electiva",
		UC: 2,
		Tax: "TA-4",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Corrección de Textos",
		UC: 3,
		Tax: "TA-6",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Gestión Cultural",
		UC: 3,
		Tax: "TA-5",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Literatura General: siglo XXI",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Literatura Latinoamericana: Siglo XXI",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Literatura Venezolana: Siglo XXI",
		UC: 4,
		Tax: "TA-1",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Seminario de Trabajo de Grado I",
		UC: 2,
		Tax: "TA-9",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Pasantía",
		UC: 3,
		Tax: "TA-7",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Electiva",
		UC: 2,
		Tax: "TA-4",
	},
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Investigación en Ciencias Sociales",
		UC: 4,
		Tax: "TA-8",
	},
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Prácticas Profesionales",
		UC: 6,
		Tax: "TA-7",
	},
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Seminario de Trabajo de Grado II",
		UC: 2,
		Tax: "TA-9",
	},
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Práctica en Psicología Clínica",
		UC: 4,
		Tax: "TA-8",
	},
];
