var sociologia = [
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Introducción a la Metodología de la Investigación Social",
		UC: 4,
		Tax: "TA ‐ 8",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso I",
		UC: 3,
		Tax: "TA ‐ 1",
	},
	{
		Semestre: "PRIMER SEMESTRE",
		Asignatura: "Comprensión Lectora y Redacción",
		UC: 5,
		Tax: "TA ‐ 6",
	},
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Sociología I", UC: 5, Tax: "TA ‐ 1" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Matemáticas I", UC: 8, Tax: "TA ‐ 6" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Historia Antigua", UC: 5, Tax: "TA ‐ 5" },
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Práctica I: Trabajo de Campo",
		UC: 3,
		Tax: "TA ‐ 8",
	},
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Identidad, Liderazgo y Compromiso II",
		UC: 3,
		Tax: "TA ‐ 1",
	},
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Estadística I", UC: 5, Tax: "TA ‐ 5" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Microeconomía I", UC: 7, Tax: "TA ‐ 1" },
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Historia de los Hechos Económicos y Sociales I",
		UC: 4,
		Tax: "TA ‐ 5",
	},
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Sociología II", UC: 6, Tax: "TA ‐ 1" },
	{
		Semestre: "SEGUNDO SEMESTRE",
		Asignatura: "Filosofía Social y Política",
		UC: 4,
		Tax: "TA ‐ 1",
	},
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Metodología de la Investigación Social I: Enfoques Cuantitativos",
		UC: 5,
		Tax: "TA ‐ 8",
	},
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Estadística II", UC: 5, Tax: "TA ‐ 5" },
	{
		Semestre: "TERCER SEMESTRE",
		Asignatura: "Historia de los Hechos Económicos y Sociales II",
		UC: 4,
		Tax: "TA ‐ 5",
	},
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Macroeconomía I", UC: 7, Tax: "TA ‐ 1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Teorías Políticas", UC: 5, Tax: "TA ‐ 1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Sociología III", UC: 6, Tax: "TA ‐ 1" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Metodología de la Investigación Social II: Enfoques Cuantitativos",
		UC: 5,
		Tax: "TA ‐ 8",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Estadística III", UC: 5, Tax: "TA ‐ 5" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Historia de América Latina", UC: 5, Tax: "TA ‐ 5" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Psicología Social", UC: 5, Tax: "TA ‐ 3" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Antropología Social y Cultural",
		UC: 4,
		Tax: "TA ‐ 3",
	},
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Sociología IV", UC: 6, Tax: "TA ‐ 1" },
	{
		Semestre: "CUARTO SEMESTRE",
		Asignatura: "Ecología, Ambiente y Sustentabilidad",
		UC: 3,
		Tax: "TA ‐ 1",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Metodología de la Investigación Social III: Enfoques Cuantitativos",
		UC: 5,
		Tax: "TA ‐ 8",
	},
	{
		Semestre: "QUINTO SEMESTRE",
		Asignatura: "Innovación y emprendimiento",
		UC: 3,
		Tax: "TA ‐ 1",
	},
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Estadística Multivariable", UC: 5, Tax: "TA ‐ 5" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Desarrollo Social", UC: 4, Tax: "TA ‐ 3" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Cambio Social en Venezuela", UC: 4, Tax: "TA ‐ 1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Demografía", UC: 4, Tax: "TA ‐ 3" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Sociología V", UC: 6, Tax: "TA ‐ 1" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Teorías de la Organización", UC: 3, Tax: "TA ‐ 1" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Metodología de la Investigación Social IV: Enfoques Cualitativos",
		UC: 5,
		Tax: "TA ‐ 8",
	},
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Práctica II: Diagnóstico Social",
		UC: 4,
		Tax: "TA ‐ 8",
	},
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Políticas Públicas", UC: 5, Tax: "TA ‐ 3" },
	{
		Semestre: "SEXTO SEMESTRE",
		Asignatura: "Ambiente, Sociedad y Sustentabilidad",
		UC: 4,
		Tax: "TA ‐ 4",
	},
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Sociología VI", UC: 6, Tax: "TA ‐ 1" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Sociología Política", UC: 5, Tax: "TA ‐ 1" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Sociología de la Desviación", UC: 4, Tax: "TA ‐ 1" },
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Seminario de Trabajo de Grado",
		UC: 4,
		Tax: "TA ‐ 8",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Asociativismo y Emprendimiento Social",
		UC: 3,
		Tax: "TA ‐ 8",
	},
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Metodología de la Investigación Social V: Enfoques Cualitativos Avanzados",
		UC: 5,
		Tax: "TA ‐ 8",
	},
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Sociología VII", UC: 6, Tax: "TA ‐ 1" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Electiva", UC: 4, Tax: "TA ‐ 8" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "(Virtual) Electiva", UC: 4, Tax: "(V) TA ‐ 8" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Planificación", UC: 5, Tax: "TA ‐ 3" },
	{
		Semestre: "SÉPTIMO SEMESTRE",
		Asignatura: "Práctica de Intervención I",
		UC: 3,
		Tax: "TA ‐ 8",
	},
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Ética Profesional", UC: 4, Tax: "TA ‐ 1" },
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Ética Profesional (Virtual)",
		UC: 4,
		Tax: "(V) TA ‐ 1",
	},
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Sociología del Conocimiento",
		UC: 4,
		Tax: "TA ‐ 1",
	},
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Sociología VIII", UC: 6, Tax: "TA ‐ 1" },
	{
		Semestre: "OCTAVO SEMESTRE",
		Asignatura: "Práctica de Intervención II",
		UC: 3,
		Tax: "TA ‐ 8",
	},
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Electiva", UC: 4, Tax: "TA ‐ 8" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "(Virtual) Electiva", UC: 4, Tax: "(V) TA ‐ 8" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Electiva", UC: 4, Tax: "TA ‐ 8" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "(Virtual) Electiva", UC: 4, Tax: "(V) TA ‐ 8" },
];

var sociologianuevopensum = [
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Identidad, Liderazgo y Compromiso I", UC: 3, Tax: "TA‐1" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Competencia Textual en Español", UC: 5, Tax: "TA‐6" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Ecología, Ambiente y Sustentabilidad", UC: 3, Tax: "TA‐1" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Innovación y Emprendimiento", UC: 3, Tax: "TA‐1" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Teoría de Conjuntos y Aplicaciones", UC: 4, Tax: "TA‐5" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Sociología: Pensamiento y Acción", UC: 4, Tax: "TA‐1" },
	{ Semestre: "PRIMER SEMESTRE", Asignatura: "Cultura Occidental I", UC: 5, Tax: "TA‐1" },

	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Identidad, Liderazgo y Compromiso II", UC: 3, Tax: "TA‐1" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Estadística I", UC: 5, Tax: "TA‐5" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Macroeconomía I", UC: 7, Tax: "TA‐1" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Historia de los Hechos Económicos y Sociales I", UC: 4, Tax: "TA‐5" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Sociología Política", UC: 4, Tax: "TA‐1" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Sociología Clásica", UC: 5, Tax: "TA‐1" },
	{ Semestre: "SEGUNDO SEMESTRE", Asignatura: "Metodología de la Investigación: Fundamentos", UC: 4, Tax: "TA‐8" },

	{ Semestre: "TERCER SEMESTRE", Asignatura: "Estadística II", UC: 5, Tax: "TA‐5" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Psicología Social", UC: 5, Tax: "TA‐1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Historia de los Hechos Económicos y Sociales II", UC: 4, Tax: "TA‐5" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Sociología: Estructura Social", UC: 4, Tax: "TA‐1" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Metodología de la Investigación: Perspectiva Cualitativa", UC: 4, Tax: "TA‐8" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Fundamentos de Programación", UC: 3, Tax: "TA‐9" },
	{ Semestre: "TERCER SEMESTRE", Asignatura: "Interculturalidad y Heurística de los Movimientos Sociales", UC: 4, Tax: "TA‐3" },

	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Sociología: Cambio Social", UC: 4, Tax: "TA‐1" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Estadística III", UC: 5, Tax: "TA‐5" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Metodología de la Investigación: Perspectiva Cuantitativa", UC: 4, Tax: "TA‐8" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Inteligencia Artificial: Aplicaciones", UC: 4, Tax: "TA‐8" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Análisis de Entropía Social", UC: 4, Tax: "TA‐1" },
	{ Semestre: "CUARTO SEMESTRE", Asignatura: "Estado y Gerencia Pública", UC: 4, Tax: "TA‐1" },

	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Análisis Etnográfico", UC: 4, Tax: "TA‐8" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Cooperación Multilateral para el Desarrollo", UC: 4, Tax: "TA‐3" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Sociología Aplicada a las Sociedades del Conocimiento", UC: 4, Tax: "TA‐3" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Demografía: Censo y Encuestas Nacionales", UC: 4, Tax: "TA‐8" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Mainstreaming, Resiliencia y Aceleración", UC: 4, Tax: "TA‐3" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Técnicas para el Desarrollo de Base", UC: 4, Tax: "TA‐4" },
	{ Semestre: "QUINTO SEMESTRE", Asignatura: "Sociología Aplicada a Empresas de la Creatividad", UC: 4, Tax: "TA‐3" },

	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Teoría del Cambio Social", UC: 4, Tax: "TA‐1" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Manejo de Data Social", UC: 4, Tax: "TA‐4" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Impacto Ambiental: Enfoques y Herramientas", UC: 4, Tax: "TA‐4" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Gerencia de Organizaciones de Desarrollo", UC: 4, Tax: "TA‐3" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Sistema de Información Geográfica y Visual", UC: 4, Tax: "TA‐8" },
	{ Semestre: "SEXTO SEMESTRE", Asignatura: "Ciudad y Gestión Urbana", UC: 4, Tax: "TA‐8" },

	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Gestión de Voluntariado y Compromiso Social", UC: 4, Tax: "TA‐3" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Formulación, Seguimiento y Evaluación de Proyectos Sociales", UC: 4, Tax: "TA‐3" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Sostenibilidad Económica y Levantamiento de Fondos", UC: 4, Tax: "TA‐3" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Políticas para el Desarrollo", UC: 4, Tax: "TA‐3" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Tópicos Avanzados de Sociología Contemporánea", UC: 5, Tax: "TA‐1" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Teoría Política", UC: 3, Tax: "TA‐1" },
	{ Semestre: "SÉPTIMO SEMESTRE", Asignatura: "Electiva", UC: 4, Tax: "TA‐9" },

	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Ética Profesional", UC: 4, Tax: "TA‐1" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Investigación Aplicada", UC: 4, Tax: "TA‐8" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Análisis Bajo la Perspectiva Verde - Azul", UC: 4, Tax: "TA‐3" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Desarrollo de Artefactos Cognitivos 4.0", UC: 4, Tax: "TA‐8" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Selección y Mayéutica de Proyectos Sociales", UC: 4, Tax: "TA‐9" },
	{ Semestre: "OCTAVO SEMESTRE", Asignatura: "Electiva", UC: 4, Tax: "TA‐9" },
];
